#ifndef __INC_SERVICE_H__
#define __INC_SERVICE_H__

// #define _IMPROVED_PACKET_ENCRYPTION_ // 패킷 암호화 개선
//#define __AUCTION__
#define __PET_SYSTEM__
#define __UDP_BLOCK__
#define ENABLE_NEW_AFFECT_POTION
#define __VIEW_TARGET_PLAYER_HP__
#define __VIEW_TARGET_DECIMAL_HP__
#define __SEND_TARGET_INFO__
#define __WJ_SHOW_MOB_INFO__
#define ENABLE_IPERI_AUTO_RELOAD_ADMIN_DATA
#define ENABLE_IGNORE_LOWER_BUFFS
#define ENABLE_QUEST_DIE_EVENT
#define M2BOB_PROTECTION
#define ENABLE_LANGUAGE_SYSTEM
#define LANGUAGE_MAX_NUM 2
#endif
#define HWID_ENABLED
#define ELEMENT_TARGET
#define RENEWAL_DEAD_PACKET
#define ENABLE_NEWSTUFF
#define ENABLE_NEW_ATTRIBUTES
#define NEW_CLIENT_VERSION_CHECK
#define CLIENT_VERSION "20191020" //YYYYMMdd
#define ENABLE_NEW_TYPE_OF_POTION // Permanente Buffitems an-/ausschalten
#define KEPP_SKILL_AT_WARP
#define ENABLE_SEND_TARGET_INFO_EXTENDED
#define ENABLE_QUEST_DUELL_EVENT
#define ENABLE_NEW_DUNGEON_STUFF
#define WJ_ENABLE_TRADABLE_ICON

#define DEFAULT_MOVE_SPEED	200 //default 100
#define MOVEMENT_SPEED_LIMIT	300 //default 200
#define PUSH_ITEM_SECURITY

#define ENABLE_KIMIKO_MOUNT_SYSTEM
